apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: sync-ca-pemstore
  annotations:
    policies.kyverno.io/title: Sync CA ConfigMap to All Namespaces
    policies.kyverno.io/subject: ConfigMap,Namespace
spec:
  background: true
  rules:
    - name: sync-configmap-to-new-namespaces
      match:
        any:
          - resources:
              kinds:
                - Namespace
      generate:
        apiVersion: v1
        kind: ConfigMap
        name: ca-pemstore
        namespace: "{{request.object.metadata.name}}"
        synchronize: true
        clone:
          namespace: default
          name: ca-pemstore